//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public long Id { get; set; }
        public string ReviewerName { get; set; }
        public string ReviewText { get; set; }
        public string ReviewSubject { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<int> Ratings { get; set; }
        public Nullable<long> ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
